INSERT INTO DANILAKOVRIGINYANDEXRU__DWH.S_AUTH_HISTORY 
SELECT
    DISTINCT GA.HK_L_USER_GROUP_ACTIVITY,
    GL.USER_ID_FROM,
    GL.EVENT,
    GL.EVENT_DTTM AS EVENT_DT,
    NOW() AS LOAD_DT,
    'S3' AS LOAD_SRC
FROM DANILAKOVRIGINYANDEXRU__STAGING.GROUP_LOG AS GL
LEFT JOIN DANILAKOVRIGINYANDEXRU__DWH.H_GROUPS AS HG ON GL.GROUP_ID = HG.GROUP_ID
LEFT JOIN DANILAKOVRIGINYANDEXRU__DWH.H_USERS AS HU ON GL.USER_ID = HU.USER_ID
LEFT JOIN DANILAKOVRIGINYANDEXRU__DWH.L_USER_GROUP_ACTIVITY AS GA ON HG.HK_GROUP_ID = GA.HK_GROUP_ID AND HU.HK_USER_ID = GA.HK_USER_ID
; 
