CREATE TABLE MART.F_CUSTOMER_RETENTION
(
    NEW_CUSTOMERS_COUNT            INT
    ,RETURNING_CUSTOMERS_COUNT     INT
    ,REFUNDED_CUSTOMER_COUNT       INT
    ,PERIOD_NAME                   VARCHAR(100)
    ,PERIOD_ID                     INT
    ,ITEM_ID                       INT
    ,NEW_CUSTOMERS_REVENUE         BIGINT
    ,RETURNING_CUSTOMERS_REVENUE   BIGINT
    ,CUSTOMERS_REFUNDED            INT
);