INSERT INTO mart.f_customer_retention
WITH ORDERS AS
(
    SELECT 
        S.ITEM_ID
        ,S.CUSTOMER_ID
        ,S.STATUS
        ,DC.WEEK_OF_YEAR AS PERIOD_ID
        ,SUM(PAYMENT_AMOUNT) AS PAYMENT_AMOUNT 
        ,COUNT(*) AS COUNT_
    FROM MART.F_SALES S
    LEFT JOIN MART.D_CALENDAR DC 
         ON S.DATE_ID = DC.DATE_ID 
         AND DC.DATE_ACTUAL BETWEEN DATE '{{ds}}' - 6 AND DATE '{{ds}}'
    GROUP BY 1,2,3,4
)
SELECT
    SUM(CASE WHEN COUNT_ = 1 THEN 1 END) AS NEW_CUSTOMERS_COUNT
    ,COALESCE(SUM(CASE WHEN COUNT_ > 1 THEN 1 END), 0) AS RETURNING_CUSTOMERS_COUNT
    ,COALESCE(SUM(CASE WHEN STATUS = 'refunded' THEN 1 END), 0) AS REFUNDED_CUSTOMER_COUNT
    ,'weekly' AS PERIOD_NAME
    ,PERIOD_ID
    ,ITEM_ID
    ,SUM(CASE WHEN COUNT_ = 1 THEN PAYMENT_AMOUNT END) AS NEW_CUSTOMERS_REVENUE
    ,COALESCE(SUM(CASE WHEN COUNT_ > 1 THEN PAYMENT_AMOUNT END), 0) AS RETURNING_CUSTOMERS_REVENUE
    ,COALESCE(SUM(CASE WHEN STATUS = 'refunded' THEN COUNT_ END), 0) AS CUSTOMERS_REFUNDED
FROM ORDERS S
GROUP BY 4,5,6
;