CREATE TABLE CDM.DM_COURIER_LEDGER(
    ID SERIAL PRIMARY KEY NOT NULL,
    COURIER_ID VARCHAR NOT NULL,
    COURIER_NAME VARCHAR NOT NULL,
    SETTLEMENT_YEAR SMALLINT NOT NULL,
    SETTLEMENT_MONTH SMALLINT NOT NULL CONSTRAINT DM_COURIER_LEDGER_MONTH_CHECK CHECK (SETTLEMENT_MONTH >= 1 AND SETTLEMENT_MONTH <= 12),
    ORDERS_COUNT INT NOT NULL,
    ORDERS_TOTAL_SUM NUMERIC(14,2) NOT NULL,
    RATE_AVG NUMERIC(14,2) NOT NULL,
    ORDER_PROCESSING_FEE NUMERIC(14,2) NOT NULL,
    COURIER_ORDER_SUM NUMERIC(14,2) NOT NULL,
    COURIER_TIPS_SUM NUMERIC(14,2) NOT NULL,
    COURIER_REWARD_SUM NUMERIC(14,2) NOT NULL
);