CREATE TABLE STG.DM_RESTAURANTS
(
    ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL
);

CREATE TABLE STG.DM_COURIERS
(
    ID VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL
);

CREATE TABLE STG.DM_DELIVERIES
(
    ORDER_ID VARCHAR NOT NULL,
    ORDER_TS TIMESTAMP(0) NOT NULL,
    DELIVERY_ID VARCHAR NOT NULL,
    COURIER_ID VARCHAR NOT NULL,
    ADDRESS VARCHAR NOT NULL,
    DELIVERY_TS TIMESTAMP(0) NOT NULL,
    RATE INT NOT NULL,
    SUM INT NOT NULL, 
    TIP_SUM INT NOT NULL
);

CREATE TABLE STG.OFFSET_SETTINGS
(
    SRC_NAME VARCHAR NOT NULL,
    MAX_OFFSET INT NOT NULL,
    LOAD_DTTM TIMESTAMP(0) NOT NULL
);